set(OPENSSL_FOUND TRUE)
set(OpenSSL::SSL_FOUND TRUE)
#set(POSTFIX "-1.1.1t")
set(POSTFIX "")
set(OPENSSL_ROOT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/openssl")
set(OPENSSL_INCLUDE_DIR "${OPENSSL_ROOT_DIR}/include")
set(OPENSSL_LIBRARY_DIR "${CMAKE_BINARY_DIR}/utils/openssl")
if(MINGW)
  set(OPENSSL_SSL_LIBRARY "${OPENSSL_LIBRARY_DIR}/libssl-1_1-x64.dll")
  set(OPENSSL_CRYPTO_LIBRARY "${OPENSSL_LIBRARY_DIR}/libcrypto-1_1-x64.dll")
  set(CMAKE_INSTALL_PREFIX "/home/oosman/repos/factory-installer/install-win")
  set(CMAKE_INSTALL_FULL_LIBDIR "${OPENSSL_LIBRARY_DIR}/")
  set(CMAKE_INSTALL_FULL_INCLUDEDIR "${OPENSSL_INCLUDE_DIR} ${OPENSSL_LIBRARY_DIR}/include")
elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64")
  set(OPENSSL_SSL_LIBRARY "${OPENSSL_LIBRARY_DIR}/libssl.so.1.1")
  set(OPENSSL_CRYPTO_LIBRARY "${OPENSSL_LIBRARY_DIR}/libcrypto.so.1.1")
elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64")
  set(OPENSSL_SSL_LIBRARY "${OPENSSL_ROOT_DIR}/arm-build/libssl.so.1.1")
  set(OPENSSL_CRYPTO_LIBRARY "${OPENSSL_ROOT_DIR}/arm-build/libcrypto.so.1.1")
else()
  message(FATAL_ERROR "Dont know what to do here - I quit!")
endif()
set(OPENSSL_LIBRARIES "${OPENSSL_SSL_LIBRARY} ${OPENSSL_CRYPTO_LIBRARY}")
set(HAVE_OPENSSL_DES_H TRUE)
set(HAVE_OPENSSL_AES_H TRUE)
set(OPENSSL_VERSION "1.1.1t")

if(NOT TARGET OpenSSL::SSL)
  add_library(OpenSSL::SSL SHARED IMPORTED)
  set_target_properties(OpenSSL::SSL PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
    IMPORTED_LOCATION "${OPENSSL_SSL_LIBRARY}"
    IMPORTED_IMPLIB "${OPENSSL_SSL_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_SOURCE_DIR}/utils/openssl/include"
    INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_LIBRARY_DIR}/include"
    )

  target_include_directories(OpenSSL::SSL INTERFACE
    $<INSTALL_INTERFACE:${CMAKE_SOURCE_DIR}/utils/openssl/include>
    $<INSTALL_INTERFACE:${OPENSSL_LIBRARY_DIR}/include>
    $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/utils/openssl/include>
    $<BUILD_INTERFACE:${OPENSSL_LIBRARY_DIR}/include>
    )
endif()

if(NOT TARGET OpenSSL::Crypto)
  add_library(OpenSSL::Crypto SHARED IMPORTED)
  set_target_properties(OpenSSL::Crypto PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
    IMPORTED_LOCATION "${OPENSSL_CRYPTO_LIBRARY}"
    IMPORTED_IMPLIB "${OPENSSL_CRYPTO_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_SOURCE_DIR}/utils/openssl/include"
    INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_LIBRARY_DIR}/include"
    )

  target_include_directories(OpenSSL::Crypto INTERFACE
    $<INSTALL_INTERFACE:${CMAKE_SOURCE_DIR}/utils/openssl/include>
    $<INSTALL_INTERFACE:${OPENSSL_LIBRARY_DIR}/include>
    $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/utils/openssl/include>
    $<BUILD_INTERFACE:${OPENSSL_LIBRARY_DIR}/include>
  )
endif()
